import { createClient } from '@supabase/supabase-js';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

// Try to load from environment variables first (for GitHub Actions)
// Then fall back to reading .env file (for local development)
let supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
let supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// If not in environment, try to read from .env file
if (!supabaseUrl || !supabaseAnonKey) {
  const envPath = resolve(process.cwd(), '.env');

  if (existsSync(envPath)) {
    const envContent = readFileSync(envPath, 'utf-8');
    const envVars: Record<string, string> = {};

    envContent.split('\n').forEach(line => {
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    });

    supabaseUrl = envVars.NEXT_PUBLIC_SUPABASE_URL;
    supabaseAnonKey = envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  }
}

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables. Please set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY.');
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function seed() {
  console.log('Seeding database...');

  const projects = [
    {
      title: 'Valencia Solar Park',
      summary: 'Ground-mounted solar PV facility with 150 MW capacity in Valencia region',
      country: 'ES',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 150,
      capex_eur: 120000000,
      grid_status: 'Grid application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.22,
      tags: ['PV', 'Utility-Scale', 'Spain'],
    },
    {
      title: 'Baltic Offshore Wind Farm',
      summary: '500 MW offshore wind project in the Baltic Sea',
      country: 'DE',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 500,
      capex_eur: 1500000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Consortium',
      expected_cf: 0.45,
      tags: ['Offshore Wind', 'Germany', 'Large-Scale'],
    },
    {
      title: 'Lyon Battery Storage',
      summary: '50 MW / 100 MWh lithium-ion battery storage facility',
      country: 'FR',
      technology: 'Storage',
      stage: 'Operational',
      size_mw: 50,
      capex_eur: 40000000,
      grid_status: 'Connected',
      owner_type: 'Utility',
      expected_cf: 0.85,
      tags: ['Battery', 'Storage', 'France', 'Operational'],
    },
    {
      title: 'Danube Hydro Upgrade',
      summary: 'Upgrade and expansion of existing run-of-river hydro plant',
      country: 'AT',
      technology: 'Hydro',
      stage: 'Feasibility',
      size_mw: 25,
      capex_eur: 35000000,
      grid_status: 'Existing connection',
      owner_type: 'Municipal Utility',
      expected_cf: 0.55,
      tags: ['Hydro', 'Upgrade', 'Austria'],
    },
    {
      title: 'Hamburg Green Hydrogen Hub',
      summary: '100 MW electrolyzer for green hydrogen production',
      country: 'DE',
      technology: 'Hydrogen',
      stage: 'Permitting',
      size_mw: 100,
      capex_eur: 200000000,
      grid_status: 'Grid capacity reserved',
      owner_type: 'Industrial Partnership',
      expected_cf: 0.70,
      tags: ['Hydrogen', 'Electrolyzer', 'Germany', 'Industrial'],
    },
    {
      title: 'Milan Industrial Efficiency Program',
      summary: 'Combined heat and power efficiency upgrades across 10 industrial sites',
      country: 'IT',
      technology: 'Efficiency',
      stage: 'Construction',
      size_mw: 30,
      capex_eur: 25000000,
      grid_status: 'N/A',
      owner_type: 'Corporate',
      expected_cf: 0.80,
      tags: ['Efficiency', 'CHP', 'Italy', 'Industrial'],
    },
    // Additional projects for Poland
    {
      title: 'Warsaw Solar Rooftop Portfolio',
      summary: 'Distributed solar PV across commercial and industrial rooftops',
      country: 'PL',
      technology: 'Solar',
      stage: 'Operational',
      size_mw: 45,
      capex_eur: 38000000,
      grid_status: 'Connected',
      owner_type: 'Investment Fund',
      expected_cf: 0.18,
      tags: ['Rooftop', 'C&I', 'Poland', 'Distributed'],
    },
    {
      title: 'Baltic Wind Poland',
      summary: '350 MW onshore wind farm in northern Poland',
      country: 'PL',
      technology: 'Wind',
      stage: 'Permitting',
      size_mw: 350,
      capex_eur: 450000000,
      grid_status: 'Application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.32,
      tags: ['Onshore Wind', 'Poland', 'Large-Scale'],
    },
    // Netherlands projects
    {
      title: 'Amsterdam Battery Hub',
      summary: '75 MW / 150 MWh battery storage facility near Amsterdam',
      country: 'NL',
      technology: 'Storage',
      stage: 'Construction',
      size_mw: 75,
      capex_eur: 60000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Utility',
      expected_cf: 0.90,
      tags: ['Battery', 'Netherlands', 'Grid Services'],
    },
    {
      title: 'Rotterdam Green Hydrogen Port',
      summary: '200 MW electrolyzer for port and industrial decarbonization',
      country: 'NL',
      technology: 'Hydrogen',
      stage: 'Feasibility',
      size_mw: 200,
      capex_eur: 400000000,
      grid_status: 'Pre-application',
      owner_type: 'Consortium',
      expected_cf: 0.75,
      tags: ['Hydrogen', 'Port', 'Netherlands', 'Industrial'],
    },
    // Belgium projects
    {
      title: 'Flanders Solar Park',
      summary: '80 MW ground-mounted solar farm in Flanders region',
      country: 'BE',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 80,
      capex_eur: 65000000,
      grid_status: 'Capacity reserved',
      owner_type: 'Independent Developer',
      expected_cf: 0.19,
      tags: ['Solar', 'Belgium', 'Utility-Scale'],
    },
    // Sweden projects
    {
      title: 'Stockholm District Heating Upgrade',
      summary: 'Waste-to-energy and heat pump integration for district heating',
      country: 'SE',
      technology: 'Efficiency',
      stage: 'Operational',
      size_mw: 60,
      capex_eur: 85000000,
      grid_status: 'Connected',
      owner_type: 'Municipal Utility',
      expected_cf: 0.85,
      tags: ['District Heating', 'Sweden', 'Municipal'],
    },
    {
      title: 'Norrland Wind Complex',
      summary: '450 MW onshore wind farm in northern Sweden',
      country: 'SE',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 450,
      capex_eur: 550000000,
      grid_status: 'Connected',
      owner_type: 'Utility',
      expected_cf: 0.38,
      tags: ['Onshore Wind', 'Sweden', 'Large-Scale'],
    },
    // Denmark projects
    {
      title: 'Copenhagen Offshore Wind Extension',
      summary: '400 MW offshore wind farm extension in Danish waters',
      country: 'DK',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 400,
      capex_eur: 1200000000,
      grid_status: 'Pre-application',
      owner_type: 'Utility',
      expected_cf: 0.50,
      tags: ['Offshore Wind', 'Denmark', 'Extension'],
    },
    // Portugal projects
    {
      title: 'Algarve Solar + Storage',
      summary: '120 MW solar PV with 40 MW / 80 MWh battery storage',
      country: 'PT',
      technology: 'Solar',
      stage: 'Construction',
      size_mw: 120,
      capex_eur: 110000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Independent Developer',
      expected_cf: 0.24,
      tags: ['Hybrid', 'Portugal', 'Solar+Storage'],
    },
    {
      title: 'Lisbon Hydrogen Mobility Hub',
      summary: '15 MW electrolyzer for green hydrogen refueling infrastructure',
      country: 'PT',
      technology: 'Hydrogen',
      stage: 'Permitting',
      size_mw: 15,
      capex_eur: 30000000,
      grid_status: 'Application submitted',
      owner_type: 'Consortium',
      expected_cf: 0.65,
      tags: ['Hydrogen', 'Mobility', 'Portugal'],
    },
    // More Spain projects
    {
      title: 'Andalusia Solar Cluster',
      summary: '300 MW portfolio of solar PV projects across Andalusia',
      country: 'ES',
      technology: 'Solar',
      stage: 'Construction',
      size_mw: 300,
      capex_eur: 240000000,
      grid_status: 'Multiple connections secured',
      owner_type: 'Investment Fund',
      expected_cf: 0.25,
      tags: ['Portfolio', 'Spain', 'Solar'],
    },
    {
      title: 'Basque Wind Repowering',
      summary: 'Repowering of existing wind farm with modern turbines',
      country: 'ES',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 85,
      capex_eur: 95000000,
      grid_status: 'Existing connection',
      owner_type: 'Independent Developer',
      expected_cf: 0.35,
      tags: ['Repowering', 'Spain', 'Wind'],
    },
    // More Germany projects
    {
      title: 'Bavaria Solar Agri-PV',
      summary: 'Agricultural solar project combining farming and energy production',
      country: 'DE',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 55,
      capex_eur: 48000000,
      grid_status: 'Pre-application',
      owner_type: 'Agricultural Cooperative',
      expected_cf: 0.20,
      tags: ['Agri-PV', 'Germany', 'Innovation'],
    },
    {
      title: 'North Sea Wind Phase II',
      summary: '900 MW offshore wind farm in German North Sea',
      country: 'DE',
      technology: 'Wind',
      stage: 'Permitting',
      size_mw: 900,
      capex_eur: 2700000000,
      grid_status: 'Capacity allocated',
      owner_type: 'Consortium',
      expected_cf: 0.48,
      tags: ['Offshore Wind', 'Germany', 'Large-Scale'],
    },
    // More France projects
    {
      title: 'Brittany Offshore Wind',
      summary: '600 MW floating offshore wind farm',
      country: 'FR',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 600,
      capex_eur: 2200000000,
      grid_status: 'Study phase',
      owner_type: 'Consortium',
      expected_cf: 0.42,
      tags: ['Floating Wind', 'France', 'Innovation'],
    },
    {
      title: 'Provence Solar Farm',
      summary: '180 MW solar PV facility in southern France',
      country: 'FR',
      technology: 'Solar',
      stage: 'Operational',
      size_mw: 180,
      capex_eur: 145000000,
      grid_status: 'Connected',
      owner_type: 'Utility',
      expected_cf: 0.23,
      tags: ['Solar', 'France', 'Operational'],
    },
    // Italy projects
    {
      title: 'Sicily Wind Portfolio',
      summary: '220 MW portfolio of onshore wind projects',
      country: 'IT',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 220,
      capex_eur: 285000000,
      grid_status: 'Multiple connections',
      owner_type: 'Investment Fund',
      expected_cf: 0.28,
      tags: ['Portfolio', 'Italy', 'Wind'],
    },
    {
      title: 'Po Valley Biomass CHP',
      summary: 'Agricultural waste biomass combined heat and power plant',
      country: 'IT',
      technology: 'Efficiency',
      stage: 'Operational',
      size_mw: 12,
      capex_eur: 18000000,
      grid_status: 'Connected',
      owner_type: 'Agricultural Cooperative',
      expected_cf: 0.75,
      tags: ['Biomass', 'CHP', 'Italy'],
    },
    // Austria additional
    {
      title: 'Alpine Pumped Hydro Storage',
      summary: 'Pumped hydro energy storage facility in Austrian Alps',
      country: 'AT',
      technology: 'Hydro',
      stage: 'Permitting',
      size_mw: 400,
      capex_eur: 650000000,
      grid_status: 'Pre-application',
      owner_type: 'Utility',
      expected_cf: 0.30,
      tags: ['Pumped Hydro', 'Storage', 'Austria'],
    },
    // Greece projects
    {
      title: 'Crete Solar Complex',
      summary: '250 MW solar PV with battery storage on Crete island',
      country: 'GR',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 250,
      capex_eur: 225000000,
      grid_status: 'Application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.26,
      tags: ['Island', 'Greece', 'Hybrid'],
    },
    {
      title: 'Aegean Wind Farm',
      summary: '150 MW onshore wind farm in mainland Greece',
      country: 'GR',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 150,
      capex_eur: 195000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Independent Developer',
      expected_cf: 0.30,
      tags: ['Wind', 'Greece', 'Onshore'],
    },
    // Ireland projects
    {
      title: 'Cork Offshore Wind',
      summary: '500 MW offshore wind farm off Irish coast',
      country: 'IE',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 500,
      capex_eur: 1600000000,
      grid_status: 'Study phase',
      owner_type: 'Utility',
      expected_cf: 0.46,
      tags: ['Offshore Wind', 'Ireland', 'Large-Scale'],
    },
    // Romania project
    {
      title: 'Bucharest Solar Park',
      summary: '100 MW solar PV facility near Bucharest',
      country: 'RO',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 100,
      capex_eur: 80000000,
      grid_status: 'Application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.21,
      tags: ['Solar', 'Romania', 'Utility-Scale'],
    },
  ];

  const investors = [
    {
      name: 'Copenhagen Infrastructure Partners',
      summary: 'World\'s largest dedicated fund manager within greenfield renewable energy investments managing EUR 33bn across 13 funds',
      ticket_min_eur: 50000000,
      ticket_max_eur: 500000000,
      geographies: ['All EU', 'Global'],
      tech_focus: ['Wind', 'Solar', 'Storage', 'Hydrogen'],
      mandate_types: ['Equity'],
      irr_target: 12,
      tags: ['Infrastructure', 'Large-Scale', 'Offshore Wind', 'Global Leader'],
      email: '[email protected]',
      phone: '+45 70 70 51 51',
      website: 'https://www.cip.com',
      headquarters: 'Copenhagen, Denmark',
      contact_person: 'Investor Relations',
      linkedin_url: 'https://www.linkedin.com/company/copenhagen-infrastructure-partners-k-s/',
    },
    {
      name: 'Schroders Greencoat',
      summary: 'One of Europe\'s largest dedicated renewable infrastructure managers with £9.6bn under management across UK, Europe and US',
      ticket_min_eur: 30000000,
      ticket_max_eur: 300000000,
      geographies: ['UK', 'IE', 'FR', 'DE', 'ES', 'DK'],
      tech_focus: ['Wind', 'Solar'],
      mandate_types: ['Equity'],
      irr_target: 9,
      tags: ['Infrastructure', 'Operational Assets', 'Listed Funds'],
      email: 'info@schrodersgreencoat.com',
      phone: '+44 20 7658 6000',
      website: 'https://www.schroderscapital.com',
      headquarters: 'London, United Kingdom',
      contact_person: 'Investment Team',
      linkedin_url: 'https://www.linkedin.com/company/schroders-greencoat/',
    },
    {
      name: 'Aquila Capital',
      summary: 'Leading European infrastructure investor managing €14.7bn with over €5bn invested in solar and wind assets, 16.6GW capacity',
      ticket_min_eur: 25000000,
      ticket_max_eur: 200000000,
      geographies: ['DE', 'ES', 'PT', 'IT', 'NL', 'NO', 'GR'],
      tech_focus: ['Solar', 'Wind', 'Hydro'],
      mandate_types: ['Equity'],
      irr_target: 10,
      tags: ['Infrastructure', 'Clean Energy', 'Listed Vehicles'],
      email: '[email protected]',
      phone: '+49 40 87 5050-100',
      website: 'https://www.aquila-capital.de',
      headquarters: 'Hamburg, Germany',
      contact_person: 'Infrastructure Team',
      linkedin_url: 'https://www.linkedin.com/company/aquila-capital/',
    },
    {
      name: 'Qualitas Energy',
      summary: 'Leading global investment platform with €14bn dedicated to energy transition, 14GW portfolio across Europe and Americas',
      ticket_min_eur: 20000000,
      ticket_max_eur: 300000000,
      geographies: ['ES', 'DE', 'UK', 'IT', 'PL'],
      tech_focus: ['Solar', 'Wind', 'Storage', 'Hydro'],
      mandate_types: ['Equity', 'Project Finance'],
      irr_target: 11,
      tags: ['Infrastructure', 'Large-Scale', 'Multi-Technology'],
      email: '[email protected]',
      phone: '+34 91 769 5300',
      website: 'https://qualitasenergy.com',
      headquarters: 'Madrid, Spain',
      contact_person: 'Investment Relations',
      linkedin_url: 'https://www.linkedin.com/company/qualitas-energy/',
    },
    {
      name: 'Encavis AG',
      summary: 'Leading independent power producer in European renewable sector, managing 3.4GW+ across solar parks and onshore wind farms',
      ticket_min_eur: 15000000,
      ticket_max_eur: 150000000,
      geographies: ['DE', 'IT', 'FR', 'NL', 'DK', 'FI', 'ES', 'AT'],
      tech_focus: ['Solar', 'Wind'],
      mandate_types: ['Equity'],
      irr_target: 9,
      tags: ['IPP', 'Operational Assets', 'Listed Company'],
      email: '[email protected]',
      phone: '+49 40 3785 620',
      website: 'https://www.encavis.com',
      headquarters: 'Hamburg, Germany',
      contact_person: 'Asset Management Team',
      linkedin_url: 'https://www.linkedin.com/company/encavis-ag/',
    },
    {
      name: 'Mirova',
      summary: 'Global sustainable investment firm with €3.5bn in energy transition infrastructure, financing 1,000+ projects across 48 countries',
      ticket_min_eur: 10000000,
      ticket_max_eur: 100000000,
      geographies: ['FR', 'ES', 'PT', 'IT', 'PL', 'DE'],
      tech_focus: ['Solar', 'Wind', 'Storage'],
      mandate_types: ['Equity'],
      irr_target: 11,
      tags: ['ESG', 'Sustainable Finance', 'Energy Transition'],
      email: '[email protected]',
      phone: '+33 1 58 19 09 80',
      website: 'https://www.mirova.com',
      headquarters: 'Paris, France',
      contact_person: 'Energy Transition Infrastructure Team',
      linkedin_url: 'https://www.linkedin.com/company/mirova/',
    },
    {
      name: 'InfraVia Capital Partners',
      summary: 'Independent European private equity firm with €10bn+ AUM investing in energy transition including renewables and decarbonization',
      ticket_min_eur: 20000000,
      ticket_max_eur: 150000000,
      geographies: ['FR', 'IT', 'ES', 'DE', 'SE', 'NL'],
      tech_focus: ['Wind', 'Solar'],
      mandate_types: ['Equity'],
      irr_target: 13,
      tags: ['Private Equity', 'Infrastructure', 'Energy Transition'],
      email: '[email protected]',
      phone: '+33 1 53 43 73 03',
      website: 'https://infraviacapital.com',
      headquarters: 'Paris, France',
      contact_person: 'Investment Team',
      linkedin_url: 'https://www.linkedin.com/company/infravia-capital-partners/',
    },
    {
      name: 'Ardian Infrastructure',
      summary: 'Major European infrastructure investor with $20bn latest fund, over 8.2GW renewable capacity including Akuo and Energia Group',
      ticket_min_eur: 50000000,
      ticket_max_eur: 500000000,
      geographies: ['FR', 'ES', 'IT', 'UK', 'IE', 'DE'],
      tech_focus: ['Wind', 'Solar', 'Storage', 'Hydro'],
      mandate_types: ['Equity'],
      irr_target: 11,
      tags: ['Infrastructure', 'Large-Scale', 'Institutional'],
      email: '[email protected]',
      phone: '+33 1 41 71 92 00',
      website: 'https://www.ardian.com',
      headquarters: 'Paris, France',
      contact_person: 'Infrastructure Team',
      linkedin_url: 'https://www.linkedin.com/company/ardian/',
    },
    {
      name: 'EQT Infrastructure',
      summary: 'Major European infrastructure investor with €21.5bn Fund VI focusing on energy transition, including OX2 and renewable platforms',
      ticket_min_eur: 100000000,
      ticket_max_eur: 2000000000,
      geographies: ['All EU', 'Global'],
      tech_focus: ['Wind', 'Solar', 'Storage', 'Hydrogen'],
      mandate_types: ['Equity'],
      irr_target: 12,
      tags: ['Large-Scale', 'Infrastructure', 'Energy Transition'],
      email: '[email protected]',
      phone: '+46 8 506 55 300',
      website: 'https://eqtgroup.com',
      headquarters: 'Stockholm, Sweden',
      contact_person: 'Infrastructure Investment Team',
      linkedin_url: 'https://www.linkedin.com/company/eqt-group/',
    },
    {
      name: 'Octopus Energy Generation',
      summary: 'One of Europe\'s largest investors in renewables managing 400+ green generators, £3bn invested across 19 countries',
      ticket_min_eur: 15000000,
      ticket_max_eur: 150000000,
      geographies: ['UK', 'FR', 'ES', 'IT', 'NL', 'IE', 'SE'],
      tech_focus: ['Wind', 'Solar'],
      mandate_types: ['Equity'],
      irr_target: 10,
      tags: ['Renewables', 'Operational Assets', 'Listed Trust'],
      email: '[email protected]',
      phone: '+44 20 4530 8369',
      website: 'https://www.octopusenergygeneration.com',
      headquarters: 'London, United Kingdom',
      contact_person: 'Investment Team',
      linkedin_url: 'https://www.linkedin.com/company/octopus-renewables/',
    },
    {
      name: 'NextEnergy Capital',
      summary: 'Leading specialist solar investment manager with 2GWp+ across 500 solar plants in UK, Europe, Americas and Asia',
      ticket_min_eur: 10000000,
      ticket_max_eur: 100000000,
      geographies: ['UK', 'IT', 'PT', 'PL', 'ES'],
      tech_focus: ['Solar', 'Storage'],
      mandate_types: ['Equity'],
      irr_target: 11,
      tags: ['Solar Specialist', 'Listed Fund', 'Battery Storage'],
      email: '[email protected]',
      phone: '+44 20 3780 0520',
      website: 'https://www.nextenergycapital.com',
      headquarters: 'London, United Kingdom',
      contact_person: 'Investment Team',
      linkedin_url: 'https://www.linkedin.com/company/nextenergy-capital/',
    },
    {
      name: 'Glennmont Partners',
      summary: 'Europe\'s largest clean energy-focused fund manager with €4bn+ AUM, 113 projects implemented across wind, solar and hydro',
      ticket_min_eur: 20000000,
      ticket_max_eur: 150000000,
      geographies: ['UK', 'FR', 'ES', 'IT', 'NL', 'SE', 'FI'],
      tech_focus: ['Wind', 'Solar', 'Hydro'],
      mandate_types: ['Equity'],
      irr_target: 10,
      tags: ['Clean Energy', 'Infrastructure', 'Greenfield'],
      email: '[email protected]',
      phone: '+44 20 7809 9060',
      website: 'https://www.glennmont.com',
      headquarters: 'London, United Kingdom',
      contact_person: 'Investment Relations',
      linkedin_url: 'https://www.linkedin.com/company/glennmont-partners/',
    },
    {
      name: 'Antin Infrastructure Partners',
      summary: 'Major European infrastructure investor with €31bn AUM, active in renewable energy including Blue Elephant Energy portfolio',
      ticket_min_eur: 50000000,
      ticket_max_eur: 500000000,
      geographies: ['FR', 'DE', 'ES', 'IT', 'UK'],
      tech_focus: ['Wind', 'Solar'],
      mandate_types: ['Equity'],
      irr_target: 12,
      tags: ['Infrastructure', 'Large-Scale', 'Listed'],
      email: '[email protected]',
      phone: '+33 1 70 08 13 00',
      website: 'https://www.antin-ip.com',
      headquarters: 'Paris, France',
      contact_person: 'Investment Relations',
      linkedin_url: 'https://www.linkedin.com/company/antin-infrastructure-partners/',
    },
    {
      name: 'Golding Capital Partners',
      summary: 'European alternative investment manager with €14bn AUM, €300m dedicated energy transition fund of funds',
      ticket_min_eur: 5000000,
      ticket_max_eur: 50000000,
      geographies: ['DE', 'FR', 'ES', 'IT', 'NL'],
      tech_focus: ['Solar', 'Wind', 'Storage'],
      mandate_types: ['Equity'],
      irr_target: 13,
      tags: ['Fund of Funds', 'Energy Transition', 'Co-Investment'],
      email: '[email protected]',
      phone: '+49 89 419 997 0',
      website: 'https://www.goldingcapital.com',
      headquarters: 'Munich, Germany',
      contact_person: 'Investment Team',
      linkedin_url: 'https://www.linkedin.com/company/golding-capital-partners/',
    },
    {
      name: 'BlackRock Global Renewable Power',
      summary: 'Major global infrastructure investor with $4.8bn Fund III, 250+ wind and solar projects across 13 countries',
      ticket_min_eur: 75000000,
      ticket_max_eur: 500000000,
      geographies: ['All EU', 'Global'],
      tech_focus: ['Wind', 'Solar', 'Storage'],
      mandate_types: ['Equity'],
      irr_target: 10,
      tags: ['Global', 'Large-Scale', 'Institutional'],
      email: '[email protected]',
      phone: '+44 20 7743 3000',
      website: 'https://www.blackrock.com',
      headquarters: 'London, UK',
      contact_person: 'Real Assets Infrastructure Team',
      linkedin_url: 'https://www.linkedin.com/company/blackrock/',
    },
  ];

  const suppliers = [
    {
      name: 'Vestas Wind Systems',
      role: 'OEM',
      summary: 'Global leader in sustainable energy solutions, manufacturer of wind turbines',
      geographies: ['All EU', 'Global'],
      technologies: ['Wind'],
      capacity_mw_py: 15000,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
        { name: 'IEC 61400 Certification', issuer: 'IEC', year: 2024 },
      ],
      tags: ['Wind Turbines', 'OEM', 'Market Leader'],
      email: 'vestas-centraleurope@vestas.com',
      phone: '+45 97 30 00 00',
      website: 'https://www.vestas.com',
      headquarters: 'Aarhus, Denmark',
      contact_person: 'Sales Department',
      linkedin_url: 'https://www.linkedin.com/company/vestas',
    },
    {
      name: 'Siemens Gamesa Renewable Energy',
      role: 'OEM',
      summary: 'Leading manufacturer of wind turbines for onshore and offshore applications',
      geographies: ['All EU', 'Global'],
      technologies: ['Wind'],
      capacity_mw_py: 12000,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
        { name: 'IEC 61400 Certification', issuer: 'IEC', year: 2024 },
      ],
      tags: ['Wind Turbines', 'OEM', 'Offshore Wind'],
      email: '[email protected]',
      phone: '+34 94 478 2800',
      website: 'https://www.siemensgamesa.com',
      headquarters: 'Zamudio, Spain',
      contact_person: 'Commercial Department',
      linkedin_url: 'https://www.linkedin.com/company/siemensgamesa',
    },
    {
      name: 'Nordex Group',
      role: 'OEM',
      summary: 'Manufacturer of multi-megawatt onshore wind turbines',
      geographies: ['All EU', 'Global'],
      technologies: ['Wind'],
      capacity_mw_py: 5000,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
        { name: 'IEC 61400 Certification', issuer: 'IEC', year: 2024 },
      ],
      tags: ['Wind Turbines', 'OEM', 'Onshore'],
      email: 'info@nordex-online.com',
      phone: '+49 40 300 30 1000',
      website: 'https://www.nordex-online.com',
      headquarters: 'Hamburg, Germany',
      contact_person: 'Sales Team',
      linkedin_url: 'https://www.linkedin.com/company/nordex',
    },
    {
      name: 'Enercon GmbH',
      role: 'OEM',
      summary: 'Pioneer in wind energy technology, manufacturer of gearless wind turbines',
      geographies: ['All EU'],
      technologies: ['Wind'],
      capacity_mw_py: 3000,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Wind Turbines', 'OEM', 'Gearless Technology'],
      email: 'info@enercon.de',
      phone: '+49 4941 9270',
      website: 'https://www.enercon.de',
      headquarters: 'Aurich, Germany',
      contact_person: 'International Sales',
      linkedin_url: 'https://www.linkedin.com/company/enercon',
    },
    {
      name: 'Ørsted',
      role: 'EPC',
      summary: 'World\'s largest developer of offshore wind power and Europe\'s leading renewable energy company',
      geographies: ['DK', 'DE', 'UK', 'NL', 'BE', 'SE', 'PL', 'Global'],
      technologies: ['Wind', 'Solar'],
      credentials: [
        { name: 'ISO 14001', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Offshore Wind', 'EPC', 'Developer', 'Market Leader'],
      email: 'info@orsted.dk',
      phone: '+45 99 55 11 11',
      website: 'https://orsted.com',
      headquarters: 'Fredericia, Denmark',
      contact_person: 'Business Development',
      linkedin_url: 'https://www.linkedin.com/company/orsted',
    },
    {
      name: 'Belectric',
      role: 'EPC',
      summary: 'Leading European solar EPC contractor with over 4 GW of installed capacity since 2001',
      geographies: ['DE', 'SE', 'NL', 'PL', 'RO', 'ES', 'IT', 'Global'],
      technologies: ['Solar', 'Storage'],
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Solar', 'EPC', 'Utility-Scale', 'Germany'],
      email: 'info@belectric.com',
      phone: '+49 9385 5489-000',
      website: 'https://belectric.com',
      headquarters: 'Kolitzheim, Germany',
      contact_person: 'Esther Jantosch - Head of Sales Central Europe',
      linkedin_url: 'https://www.linkedin.com/company/belectric-gmbh',
    },
    {
      name: 'RES (Renewable Energy Systems)',
      role: 'EPC',
      summary: 'World\'s largest independent renewable energy company with 23 GW delivered globally, 12 GW operational portfolio',
      geographies: ['UK', 'IE', 'FR', 'DE', 'ES', 'IT', 'PL', 'SE', 'Global'],
      technologies: ['Wind', 'Solar', 'Storage'],
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
        { name: 'ISO 14001', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Wind', 'Solar', 'EPC', 'Independent', 'Large-Scale'],
      email: 'info@res-group.com',
      phone: '+44 1923 299 200',
      website: 'https://www.res-group.com',
      headquarters: 'Kings Langley, UK',
      contact_person: 'Rachel Anderson - Head of Corporate Communications',
      linkedin_url: 'https://www.linkedin.com/company/res-group',
    },
    {
      name: 'Acciona Energía',
      role: 'EPC',
      summary: 'Spanish renewable energy developer and EPC contractor with expertise across wind, solar, hydro and biomass',
      geographies: ['ES', 'PT', 'IT', 'PL', 'Global'],
      technologies: ['Wind', 'Solar', 'Hydro', 'Efficiency'],
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
        { name: 'ISO 14001', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Wind', 'Solar', 'EPC', 'Spain', 'Multi-Technology'],
      email: 'protecciondedatosenergia@acciona.com',
      phone: '+34 91 657 64 61',
      website: 'https://www.acciona-energia.com',
      headquarters: 'Madrid, Spain',
      contact_person: 'Ignacio Domecq - Business Development',
      linkedin_url: 'https://www.linkedin.com/company/acciona',
    },
    {
      name: 'Enel Green Power',
      role: 'EPC',
      summary: 'Italian renewable energy giant managing 67.2 GW capacity globally across solar, wind, hydro and geothermal',
      geographies: ['IT', 'ES', 'GR', 'RO', 'Global'],
      technologies: ['Solar', 'Wind', 'Hydro', 'Efficiency'],
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
        { name: 'ISO 14001', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Multi-Technology', 'EPC', 'Italy', 'Large-Scale', 'Utility'],
      email: 'info@enelgreenpower.com',
      phone: '+39 06 83051',
      website: 'https://www.enelgreenpower.com',
      headquarters: 'Rome, Italy',
      contact_person: 'Regional Communications',
      linkedin_url: 'https://www.linkedin.com/company/enel_green_power',
    },
    {
      name: 'SMA Solar Technology',
      role: 'OEM',
      summary: 'Leading German solar inverter manufacturer with 40 GW annual production capacity',
      geographies: ['All EU', 'Global'],
      technologies: ['Solar', 'Storage'],
      capacity_mw_py: 40000,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
        { name: 'IEC 62109 Certification', issuer: 'IEC', year: 2024 },
      ],
      tags: ['Solar Inverters', 'OEM', 'Germany', 'Market Leader'],
      email: 'socialmedia@sma.de',
      phone: '+49 561 95220',
      website: 'https://www.sma.de',
      headquarters: 'Niestetal, Germany',
      contact_person: 'Sales Department',
      linkedin_url: 'https://www.linkedin.com/company/sma-solar-technology-ag',
    },
    {
      name: 'Meyer Burger',
      role: 'OEM',
      summary: 'Swiss-German solar panel manufacturer with advanced heterojunction technology and 100% renewable energy production',
      geographies: ['All EU'],
      technologies: ['Solar'],
      capacity_mw_py: 1400,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Solar Panels', 'OEM', 'Switzerland', 'Premium Quality'],
      email: 'info-thun@meyerburger.com',
      phone: '+41 33 221 28 00',
      website: 'https://www.meyerburger.com',
      headquarters: 'Thun, Switzerland',
      contact_person: 'Sales Team',
      linkedin_url: 'https://www.linkedin.com/company/meyer-burger',
    },
    {
      name: 'Apricum - The Cleantech Advisory',
      role: 'Consulting',
      summary: 'Global transaction and strategy advisory firm dedicated to renewable energy and cleantech with 250+ projects completed',
      geographies: ['All EU', 'Global'],
      technologies: ['Solar', 'Wind', 'Storage', 'Hydrogen', 'Efficiency'],
      credentials: [],
      tags: ['M&A Advisory', 'Strategy', 'Consulting', 'Transaction Advisory'],
      email: 'info@apricum-group.com',
      phone: '+49 30 30 877 620',
      website: 'https://apricum-group.com',
      headquarters: 'Berlin, Germany',
      contact_person: 'Advisory Team',
      linkedin_url: 'https://www.linkedin.com/company/apricum-gmbh',
    },
    {
      name: 'DNV Energy Systems',
      role: 'Consulting',
      summary: 'Norwegian technical advisory and certification leader delivering testing and consulting services across renewable energy value chain',
      geographies: ['All EU', 'Global'],
      technologies: ['Wind', 'Solar', 'Hydrogen', 'Storage', 'Hydro'],
      credentials: [
        { name: 'ISO/IEC 17025 Accreditation', issuer: 'ISO', year: 2024 },
      ],
      tags: ['Technical Advisory', 'Certification', 'Due Diligence', 'Testing'],
      email: 'info@dnv.com',
      phone: '+47 67 57 99 00',
      website: 'https://www.dnv.com',
      headquarters: 'Oslo, Norway',
      contact_person: 'Energy Systems Division',
      linkedin_url: 'https://www.linkedin.com/company/dnv',
    },
    {
      name: 'Pexapark',
      role: 'Consulting',
      summary: 'Swiss renewable energy market intelligence and advisory specialist supporting over 30 GW of PPA transactions',
      geographies: ['All EU'],
      technologies: ['Solar', 'Wind', 'Storage'],
      credentials: [],
      tags: ['PPA Advisory', 'Market Intelligence', 'Risk Management', 'Software'],
      email: 'hello@pexapark.com',
      phone: '+41 43 508 3255',
      website: 'https://pexapark.com',
      headquarters: 'Zurich, Switzerland',
      contact_person: 'Advisory Team',
      linkedin_url: 'https://www.linkedin.com/company/pexapark',
    },
  ];

  const policyBriefs = [
    {
      country: 'ES',
      country_name: 'Spain',
      incentives: [
        {
          name: 'PERTE Renovables',
          description: 'Strategic project for renewable energy and green hydrogen',
          eligibility: 'Projects above 5 MW with domestic content requirements',
          amount: 'Up to 30% CAPEX grant',
        },
      ],
      permitting_steps: [
        {
          step: 1,
          name: 'Environmental Impact Assessment',
          description: 'Submit EIA documentation to regional authority',
          typical_duration: '6-12 months',
          agency: 'Regional Environmental Agency',
        },
        {
          step: 2,
          name: 'Grid Access Permit',
          description: 'Apply for grid connection point and capacity allocation',
          typical_duration: '3-6 months',
          agency: 'Red Eléctrica de España',
        },
        {
          step: 3,
          name: 'Construction Permit',
          description: 'Obtain local construction authorization',
          typical_duration: '2-4 months',
          agency: 'Municipal Authority',
        },
      ],
      avg_lead_times: {
        solar: '12-18 months',
        wind: '18-36 months',
      },
      agencies: [
        { name: 'MITECO', role: 'National energy and environment ministry', website: 'miteco.gob.es' },
        { name: 'IDAE', role: 'Energy efficiency and renewable promotion', website: 'idae.es' },
      ],
      sources: [
        { title: 'Royal Decree 1183/2020 on Grid Access', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2020-17771' },
        { title: 'PERTE ERHA Information (IDAE)', url: 'https://www.idae.es/ayudas-y-financiacion/para-empresas/perte-erha' },
        { title: 'Spanish NECP 2021-2030', url: 'https://energy.ec.europa.eu/system/files/2020-06/es_final_necp_main_en_0.pdf' },
      ],
    },
    {
      country: 'DE',
      country_name: 'Germany',
      incentives: [
        {
          name: 'EEG Feed-in Premium',
          description: 'Market premium for renewable electricity',
          eligibility: 'Competitive auction participation',
          amount: 'Variable, auction-determined',
        },
        {
          name: 'H2Global Program',
          description: 'Support for green hydrogen imports and domestic production',
          eligibility: 'Hydrogen projects with verified green credentials',
          amount: 'Price differential contracts',
        },
      ],
      permitting_steps: [
        {
          step: 1,
          name: 'BImSchG Approval',
          description: 'Federal Immission Control Act permit for large installations',
          typical_duration: '6-12 months',
          agency: 'State Environmental Authority',
        },
        {
          step: 2,
          name: 'Grid Connection Agreement',
          description: 'Secure connection with TSO or DSO',
          typical_duration: '4-8 months',
          agency: 'Transmission/Distribution System Operator',
        },
        {
          step: 3,
          name: 'Building Permit',
          description: 'Local construction authorization',
          typical_duration: '2-3 months',
          agency: 'Local Building Authority',
        },
      ],
      avg_lead_times: {
        solar: '10-16 months',
        wind: '24-48 months',
        hydrogen: '18-30 months',
      },
      agencies: [
        { name: 'BMWi', role: 'Federal Ministry for Economic Affairs and Energy', website: 'bmwk.de' },
        { name: 'BNetzA', role: 'Federal Network Agency', website: 'bundesnetzagentur.de' },
      ],
      sources: [
        { title: 'EEG 2023 (Renewable Energy Act)', url: 'https://www.gesetze-im-internet.de/eeg_2014/index.html' },
        { title: 'German Hydrogen Strategy', url: 'https://www.bmwk.de/Redaktion/EN/Publikationen/Energie/the-national-hydrogen-strategy.html' },
        { title: 'German NECP', url: 'https://energy.ec.europa.eu/system/files/2020-03/de_final_necp_main_en_0.pdf' },
      ],
    },
    {
      country: 'FR',
      country_name: 'France',
      incentives: [
        {
          name: 'CRE Tender Program',
          description: 'Competitive tenders for renewable projects',
          eligibility: 'Projects above threshold capacity',
          amount: 'Auction-determined feed-in tariff',
        },
      ],
      permitting_steps: [
        {
          step: 1,
          name: 'Environmental Authorization',
          description: 'Unified environmental permit (permis environnemental unique)',
          typical_duration: '9-12 months',
          agency: 'Prefect / DREAL',
        },
        {
          step: 2,
          name: 'Grid Connection',
          description: 'Proposal and agreement with Enedis/RTE',
          typical_duration: '4-6 months',
          agency: 'Enedis or RTE',
        },
        {
          step: 3,
          name: 'Building Permit',
          description: 'Local construction permit (permis de construire)',
          typical_duration: '2-3 months',
          agency: 'Municipal Authority',
        },
      ],
      avg_lead_times: {
        solar: '12-18 months',
        wind: '24-36 months',
      },
      agencies: [
        { name: 'CRE', role: 'Energy Regulatory Commission', website: 'cre.fr' },
        { name: 'ADEME', role: 'Ecological Transition Agency', website: 'ademe.fr' },
      ],
      sources: [
        { title: 'French Energy Transition Law (LTECV)', url: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000031044385' },
        { title: 'French NECP', url: 'https://energy.ec.europa.eu/system/files/2020-06/fr_final_necp_main_en_0.pdf' },
        { title: 'PPE - Multi-Year Energy Plan', url: 'https://www.ecologie.gouv.fr/programmations-pluriannuelles-lenergie-ppe' },
      ],
    },
  ];

  const gridBriefs = [
    {
      country: 'ES',
      country_name: 'Spain',
      steps: [
        {
          step: 1,
          name: 'Pre-application Consultation',
          description: 'Discuss project with TSO/DSO',
          typical_duration: '1 month',
        },
        {
          step: 2,
          name: 'Grid Access Request',
          description: 'Formal application and capacity check',
          typical_duration: '3-6 months',
        },
        {
          step: 3,
          name: 'Connection Agreement',
          description: 'Sign agreement and pay deposits',
          typical_duration: '2-3 months',
        },
        {
          step: 4,
          name: 'Construction and Commissioning',
          description: 'Build connection assets and test',
          typical_duration: '6-12 months',
        },
      ],
      lead_time_min_months: 12,
      lead_time_max_months: 24,
      queue_notes: 'Significant queue in high-generation areas; prioritization for storage',
      documents: [
        { name: 'Technical Project Description', description: 'Detailed technical specs and layout' },
        { name: 'Land Rights Documentation', description: 'Proof of land control or easements' },
        { name: 'Environmental Clearance', description: 'EIA approval certificate' },
      ],
      sources: [
        { title: 'REE Grid Connection Procedures', url: 'https://www.ree.es/en/activities/access-and-connection' },
      ],
    },
    {
      country: 'DE',
      country_name: 'Germany',
      steps: [
        {
          step: 1,
          name: 'Informal Inquiry',
          description: 'Initial capacity and feasibility check',
          typical_duration: '1 month',
        },
        {
          step: 2,
          name: 'Formal Application',
          description: 'Submit full connection request',
          typical_duration: '4-6 months',
        },
        {
          step: 3,
          name: 'Connection Offer',
          description: 'Receive and accept connection terms',
          typical_duration: '2-4 months',
        },
        {
          step: 4,
          name: 'Implementation',
          description: 'Build connection infrastructure',
          typical_duration: '12-18 months',
        },
      ],
      lead_time_min_months: 18,
      lead_time_max_months: 36,
      queue_notes: 'North-South bottlenecks; offshore wind has dedicated capacity',
      documents: [
        { name: 'Plant Description', description: 'Technical specs per VDE standards' },
        { name: 'Site Plan', description: 'Detailed layout and grid interface' },
        { name: 'BImSchG Permit', description: 'Environmental approval' },
      ],
      sources: [
        { title: 'BNetzA Grid Connection Info', url: 'https://www.bundesnetzagentur.de/EN/Areas/Energy/Companies/GridConnection/start.html' },
      ],
    },
    {
      country: 'FR',
      country_name: 'France',
      steps: [
        {
          step: 1,
          name: 'Pre-study Request',
          description: 'Request grid capacity assessment',
          typical_duration: '1-2 months',
        },
        {
          step: 2,
          name: 'Full Study and Proposal',
          description: 'Detailed technical and cost proposal from TSO/DSO',
          typical_duration: '4-6 months',
        },
        {
          step: 3,
          name: 'Agreement Signature',
          description: 'Sign PTF (Proposal Technique et Financière)',
          typical_duration: '2 months',
        },
        {
          step: 4,
          name: 'Works Execution',
          description: 'Grid reinforcement and connection construction',
          typical_duration: '6-12 months',
        },
      ],
      lead_time_min_months: 13,
      lead_time_max_months: 22,
      queue_notes: 'Regional variations; southern regions have faster timelines',
      documents: [
        { name: 'Project Description', description: 'Technical dossier per NF standards' },
        { name: 'Environmental Authorization', description: 'Permis environnemental unique' },
        { name: 'Land Availability', description: 'Proof of site control' },
      ],
      sources: [
        { title: 'RTE Connection Procedures', url: 'https://www.rte-france.com/en/connections-and-suppliers-portal' },
        { title: 'Enedis Connection Portal', url: 'https://www.enedis.fr/raccordement-production' },
      ],
    },
  ];

  const events = [
    {
      title: 'European Clean Energy Forum 2026',
      description: 'Annual gathering of projects, investors, and policymakers across European renewable energy',
      start_date: '2026-03-15',
      end_date: '2026-03-17',
      location: 'Brussels, Belgium',
      event_type: 'Conference',
      sessions: [
        {
          id: 's1',
          title: 'Offshore Wind: Scaling to 100 GW',
          description: 'Panel on offshore wind targets and supply chain challenges',
          start_time: '2026-03-15T09:00:00',
          end_time: '2026-03-15T10:30:00',
          track: 'Technology',
          speakers: ['Jane Doe', 'John Smith'],
        },
        {
          id: 's2',
          title: 'Green Hydrogen Economics',
          description: 'Current costs, subsidies, and pathways to competitiveness',
          start_time: '2026-03-15T11:00:00',
          end_time: '2026-03-15T12:30:00',
          track: 'Market',
          speakers: ['Maria Garcia', 'Lars Nielsen'],
        },
        {
          id: 's3',
          title: 'Permitting Reform: Progress and Gaps',
          description: 'Update on EU and member-state permitting acceleration',
          start_time: '2026-03-15T14:00:00',
          end_time: '2026-03-15T15:30:00',
          track: 'Policy',
          speakers: ['Policy Expert 1', 'Policy Expert 2'],
        },
      ],
      tags: ['Conference', 'Brussels', '2026'],
    },
  ];

  const libraryItems = [
    {
      title: 'Understanding EU Renewable Energy Directive (RED III)',
      summary: 'Plain-English breakdown of the revised Renewable Energy Directive and its implications for project developers',
      content: 'The EU Renewable Energy Directive (RED III) sets binding targets for renewable energy across member states. Key updates include accelerated permitting timelines (maximum 12 months for solar, 24 months for wind in designated areas), mandatory go-to areas for renewables, and strengthened sustainability criteria. For developers, this means streamlined processes in designated zones, but stricter environmental safeguards. Member states must transpose RED III by mid-2024, with implementation timelines varying by country. Practical impact: Projects in designated renewable acceleration areas benefit from presumed public interest and simplified environmental assessments.',
      item_type: 'Brief',
      read_time_minutes: 2,
      tags: ['Policy', 'EU', 'Permitting'],
    },
    {
      title: 'Grid Connection Queue Management Across Europe',
      summary: 'Comparative analysis of how different countries handle grid connection applications and queue priorities',
      content: 'Grid connection queues vary significantly across Europe. Germany employs a first-come-first-served model with conditional milestones, while Spain recently reformed its system to prioritize projects with advanced development status. France uses a mixed approach with regional capacity allocation. Key insight: Storage projects are increasingly receiving priority treatment due to grid stabilization benefits. Best practice for developers: secure grid capacity early, maintain milestone compliance, and consider hybrid projects (solar + storage) for preferential treatment. Typical queue times range from 12 months (France, distribution level) to 36+ months (Germany, transmission level).',
      item_type: 'Brief',
      read_time_minutes: 2,
      tags: ['Grid', 'Infrastructure', 'Permitting'],
    },
    {
      title: 'Green Hydrogen Production Costs: 2024 Benchmark',
      summary: 'Current levelized cost breakdown for electrolytic hydrogen production in Europe',
      content: 'As of 2024, green hydrogen production costs in Europe range from €4-7/kg depending on electricity prices, electrolyzer efficiency, and utilization rates. Key cost drivers: renewable electricity (50-60% of LCOH), electrolyzer CAPEX (25-30%), and O&M (10-15%). Costs are falling rapidly—electrolyzer prices dropped 40% since 2020. Pathways to competitiveness: securing low-cost PPAs (target <€30/MWh), achieving high capacity factors (>4,000 hours/year), and accessing grant support (IPCEI, H2Global). Projects with co-located renewables and merchant offtake are reaching €3.5-4.5/kg in Iberia and Northern Europe. Policy support remains critical—most projects rely on CAPEX grants or price guarantees to close the gap with grey hydrogen (€1.5-2.5/kg).',
      item_type: 'Brief',
      read_time_minutes: 3,
      tags: ['Hydrogen', 'Economics', 'Technology'],
    },
  ];

  const { error: projectsError } = await supabase.from('projects').insert(projects);
  if (projectsError) console.error('Projects error:', projectsError);
  else console.log(`✓ Inserted ${projects.length} projects`);

  const { error: investorsError } = await supabase.from('investors').insert(investors);
  if (investorsError) console.error('Investors error:', investorsError);
  else console.log(`✓ Inserted ${investors.length} investors`);

  const { error: suppliersError } = await supabase.from('suppliers').insert(suppliers);
  if (suppliersError) console.error('Suppliers error:', suppliersError);
  else console.log(`✓ Inserted ${suppliers.length} suppliers`);

  const { error: policyError } = await supabase.from('policy_briefs').insert(policyBriefs);
  if (policyError) console.error('Policy briefs error:', policyError);
  else console.log(`✓ Inserted ${policyBriefs.length} policy briefs`);

  const { error: gridError } = await supabase.from('grid_briefs').insert(gridBriefs);
  if (gridError) console.error('Grid briefs error:', gridError);
  else console.log(`✓ Inserted ${gridBriefs.length} grid briefs`);

  const { error: eventsError } = await supabase.from('events').insert(events);
  if (eventsError) console.error('Events error:', eventsError);
  else console.log(`✓ Inserted ${events.length} events`);

  const { error: libraryError } = await supabase.from('library_items').insert(libraryItems);
  if (libraryError) console.error('Library items error:', libraryError);
  else console.log(`✓ Inserted ${libraryItems.length} library items`);

  console.log('✅ Seeding complete!');
}

seed().catch(console.error);
