import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const envPath = resolve(process.cwd(), '.env');
const envContent = readFileSync(envPath, 'utf-8');
const envVars: Record<string, string> = {};

envContent.split('\n').forEach(line => {
  const [key, ...valueParts] = line.split('=');
  if (key && valueParts.length) {
    envVars[key.trim()] = valueParts.join('=').trim();
  }
});

const supabaseUrl = envVars.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function seed() {
  console.log('Seeding database...');

  const projects = [
    {
      title: 'Valencia Solar Park',
      summary: 'Ground-mounted solar PV facility with 150 MW capacity in Valencia region',
      country: 'ES',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 150,
      capex_eur: 120000000,
      grid_status: 'Grid application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.22,
      tags: ['PV', 'Utility-Scale', 'Spain'],
    },
    {
      title: 'Baltic Offshore Wind Farm',
      summary: '500 MW offshore wind project in the Baltic Sea',
      country: 'DE',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 500,
      capex_eur: 1500000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Consortium',
      expected_cf: 0.45,
      tags: ['Offshore Wind', 'Germany', 'Large-Scale'],
    },
    {
      title: 'Lyon Battery Storage',
      summary: '50 MW / 100 MWh lithium-ion battery storage facility',
      country: 'FR',
      technology: 'Storage',
      stage: 'Operational',
      size_mw: 50,
      capex_eur: 40000000,
      grid_status: 'Connected',
      owner_type: 'Utility',
      expected_cf: 0.85,
      tags: ['Battery', 'Storage', 'France', 'Operational'],
    },
    {
      title: 'Danube Hydro Upgrade',
      summary: 'Upgrade and expansion of existing run-of-river hydro plant',
      country: 'AT',
      technology: 'Hydro',
      stage: 'Feasibility',
      size_mw: 25,
      capex_eur: 35000000,
      grid_status: 'Existing connection',
      owner_type: 'Municipal Utility',
      expected_cf: 0.55,
      tags: ['Hydro', 'Upgrade', 'Austria'],
    },
    {
      title: 'Hamburg Green Hydrogen Hub',
      summary: '100 MW electrolyzer for green hydrogen production',
      country: 'DE',
      technology: 'Hydrogen',
      stage: 'Permitting',
      size_mw: 100,
      capex_eur: 200000000,
      grid_status: 'Grid capacity reserved',
      owner_type: 'Industrial Partnership',
      expected_cf: 0.70,
      tags: ['Hydrogen', 'Electrolyzer', 'Germany', 'Industrial'],
    },
    {
      title: 'Milan Industrial Efficiency Program',
      summary: 'Combined heat and power efficiency upgrades across 10 industrial sites',
      country: 'IT',
      technology: 'Efficiency',
      stage: 'Construction',
      size_mw: 30,
      capex_eur: 25000000,
      grid_status: 'N/A',
      owner_type: 'Corporate',
      expected_cf: 0.80,
      tags: ['Efficiency', 'CHP', 'Italy', 'Industrial'],
    },
    // Additional projects for Poland
    {
      title: 'Warsaw Solar Rooftop Portfolio',
      summary: 'Distributed solar PV across commercial and industrial rooftops',
      country: 'PL',
      technology: 'Solar',
      stage: 'Operational',
      size_mw: 45,
      capex_eur: 38000000,
      grid_status: 'Connected',
      owner_type: 'Investment Fund',
      expected_cf: 0.18,
      tags: ['Rooftop', 'C&I', 'Poland', 'Distributed'],
    },
    {
      title: 'Baltic Wind Poland',
      summary: '350 MW onshore wind farm in northern Poland',
      country: 'PL',
      technology: 'Wind',
      stage: 'Permitting',
      size_mw: 350,
      capex_eur: 450000000,
      grid_status: 'Application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.32,
      tags: ['Onshore Wind', 'Poland', 'Large-Scale'],
    },
    // Netherlands projects
    {
      title: 'Amsterdam Battery Hub',
      summary: '75 MW / 150 MWh battery storage facility near Amsterdam',
      country: 'NL',
      technology: 'Storage',
      stage: 'Construction',
      size_mw: 75,
      capex_eur: 60000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Utility',
      expected_cf: 0.90,
      tags: ['Battery', 'Netherlands', 'Grid Services'],
    },
    {
      title: 'Rotterdam Green Hydrogen Port',
      summary: '200 MW electrolyzer for port and industrial decarbonization',
      country: 'NL',
      technology: 'Hydrogen',
      stage: 'Feasibility',
      size_mw: 200,
      capex_eur: 400000000,
      grid_status: 'Pre-application',
      owner_type: 'Consortium',
      expected_cf: 0.75,
      tags: ['Hydrogen', 'Port', 'Netherlands', 'Industrial'],
    },
    // Belgium projects
    {
      title: 'Flanders Solar Park',
      summary: '80 MW ground-mounted solar farm in Flanders region',
      country: 'BE',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 80,
      capex_eur: 65000000,
      grid_status: 'Capacity reserved',
      owner_type: 'Independent Developer',
      expected_cf: 0.19,
      tags: ['Solar', 'Belgium', 'Utility-Scale'],
    },
    // Sweden projects
    {
      title: 'Stockholm District Heating Upgrade',
      summary: 'Waste-to-energy and heat pump integration for district heating',
      country: 'SE',
      technology: 'Efficiency',
      stage: 'Operational',
      size_mw: 60,
      capex_eur: 85000000,
      grid_status: 'Connected',
      owner_type: 'Municipal Utility',
      expected_cf: 0.85,
      tags: ['District Heating', 'Sweden', 'Municipal'],
    },
    {
      title: 'Norrland Wind Complex',
      summary: '450 MW onshore wind farm in northern Sweden',
      country: 'SE',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 450,
      capex_eur: 550000000,
      grid_status: 'Connected',
      owner_type: 'Utility',
      expected_cf: 0.38,
      tags: ['Onshore Wind', 'Sweden', 'Large-Scale'],
    },
    // Denmark projects
    {
      title: 'Copenhagen Offshore Wind Extension',
      summary: '400 MW offshore wind farm extension in Danish waters',
      country: 'DK',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 400,
      capex_eur: 1200000000,
      grid_status: 'Pre-application',
      owner_type: 'Utility',
      expected_cf: 0.50,
      tags: ['Offshore Wind', 'Denmark', 'Extension'],
    },
    // Portugal projects
    {
      title: 'Algarve Solar + Storage',
      summary: '120 MW solar PV with 40 MW / 80 MWh battery storage',
      country: 'PT',
      technology: 'Solar',
      stage: 'Construction',
      size_mw: 120,
      capex_eur: 110000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Independent Developer',
      expected_cf: 0.24,
      tags: ['Hybrid', 'Portugal', 'Solar+Storage'],
    },
    {
      title: 'Lisbon Hydrogen Mobility Hub',
      summary: '15 MW electrolyzer for green hydrogen refueling infrastructure',
      country: 'PT',
      technology: 'Hydrogen',
      stage: 'Permitting',
      size_mw: 15,
      capex_eur: 30000000,
      grid_status: 'Application submitted',
      owner_type: 'Consortium',
      expected_cf: 0.65,
      tags: ['Hydrogen', 'Mobility', 'Portugal'],
    },
    // More Spain projects
    {
      title: 'Andalusia Solar Cluster',
      summary: '300 MW portfolio of solar PV projects across Andalusia',
      country: 'ES',
      technology: 'Solar',
      stage: 'Construction',
      size_mw: 300,
      capex_eur: 240000000,
      grid_status: 'Multiple connections secured',
      owner_type: 'Investment Fund',
      expected_cf: 0.25,
      tags: ['Portfolio', 'Spain', 'Solar'],
    },
    {
      title: 'Basque Wind Repowering',
      summary: 'Repowering of existing wind farm with modern turbines',
      country: 'ES',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 85,
      capex_eur: 95000000,
      grid_status: 'Existing connection',
      owner_type: 'Independent Developer',
      expected_cf: 0.35,
      tags: ['Repowering', 'Spain', 'Wind'],
    },
    // More Germany projects
    {
      title: 'Bavaria Solar Agri-PV',
      summary: 'Agricultural solar project combining farming and energy production',
      country: 'DE',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 55,
      capex_eur: 48000000,
      grid_status: 'Pre-application',
      owner_type: 'Agricultural Cooperative',
      expected_cf: 0.20,
      tags: ['Agri-PV', 'Germany', 'Innovation'],
    },
    {
      title: 'North Sea Wind Phase II',
      summary: '900 MW offshore wind farm in German North Sea',
      country: 'DE',
      technology: 'Wind',
      stage: 'Permitting',
      size_mw: 900,
      capex_eur: 2700000000,
      grid_status: 'Capacity allocated',
      owner_type: 'Consortium',
      expected_cf: 0.48,
      tags: ['Offshore Wind', 'Germany', 'Large-Scale'],
    },
    // More France projects
    {
      title: 'Brittany Offshore Wind',
      summary: '600 MW floating offshore wind farm',
      country: 'FR',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 600,
      capex_eur: 2200000000,
      grid_status: 'Study phase',
      owner_type: 'Consortium',
      expected_cf: 0.42,
      tags: ['Floating Wind', 'France', 'Innovation'],
    },
    {
      title: 'Provence Solar Farm',
      summary: '180 MW solar PV facility in southern France',
      country: 'FR',
      technology: 'Solar',
      stage: 'Operational',
      size_mw: 180,
      capex_eur: 145000000,
      grid_status: 'Connected',
      owner_type: 'Utility',
      expected_cf: 0.23,
      tags: ['Solar', 'France', 'Operational'],
    },
    // Italy projects
    {
      title: 'Sicily Wind Portfolio',
      summary: '220 MW portfolio of onshore wind projects',
      country: 'IT',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 220,
      capex_eur: 285000000,
      grid_status: 'Multiple connections',
      owner_type: 'Investment Fund',
      expected_cf: 0.28,
      tags: ['Portfolio', 'Italy', 'Wind'],
    },
    {
      title: 'Po Valley Biomass CHP',
      summary: 'Agricultural waste biomass combined heat and power plant',
      country: 'IT',
      technology: 'Efficiency',
      stage: 'Operational',
      size_mw: 12,
      capex_eur: 18000000,
      grid_status: 'Connected',
      owner_type: 'Agricultural Cooperative',
      expected_cf: 0.75,
      tags: ['Biomass', 'CHP', 'Italy'],
    },
    // Austria additional
    {
      title: 'Alpine Pumped Hydro Storage',
      summary: 'Pumped hydro energy storage facility in Austrian Alps',
      country: 'AT',
      technology: 'Hydro',
      stage: 'Permitting',
      size_mw: 400,
      capex_eur: 650000000,
      grid_status: 'Pre-application',
      owner_type: 'Utility',
      expected_cf: 0.30,
      tags: ['Pumped Hydro', 'Storage', 'Austria'],
    },
    // Greece projects
    {
      title: 'Crete Solar Complex',
      summary: '250 MW solar PV with battery storage on Crete island',
      country: 'GR',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 250,
      capex_eur: 225000000,
      grid_status: 'Application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.26,
      tags: ['Island', 'Greece', 'Hybrid'],
    },
    {
      title: 'Aegean Wind Farm',
      summary: '150 MW onshore wind farm in mainland Greece',
      country: 'GR',
      technology: 'Wind',
      stage: 'Construction',
      size_mw: 150,
      capex_eur: 195000000,
      grid_status: 'Grid connection secured',
      owner_type: 'Independent Developer',
      expected_cf: 0.30,
      tags: ['Wind', 'Greece', 'Onshore'],
    },
    // Ireland projects
    {
      title: 'Cork Offshore Wind',
      summary: '500 MW offshore wind farm off Irish coast',
      country: 'IE',
      technology: 'Wind',
      stage: 'Feasibility',
      size_mw: 500,
      capex_eur: 1600000000,
      grid_status: 'Study phase',
      owner_type: 'Utility',
      expected_cf: 0.46,
      tags: ['Offshore Wind', 'Ireland', 'Large-Scale'],
    },
    // Romania project
    {
      title: 'Bucharest Solar Park',
      summary: '100 MW solar PV facility near Bucharest',
      country: 'RO',
      technology: 'Solar',
      stage: 'Permitting',
      size_mw: 100,
      capex_eur: 80000000,
      grid_status: 'Application submitted',
      owner_type: 'Independent Developer',
      expected_cf: 0.21,
      tags: ['Solar', 'Romania', 'Utility-Scale'],
    },
  ];

  const investors = [
    {
      name: 'Alpine Energy Partners',
      summary: 'Mid-market infrastructure fund focusing on renewable energy across Central Europe',
      ticket_min_eur: 10000000,
      ticket_max_eur: 50000000,
      geographies: ['DE', 'AT', 'CH', 'IT'],
      tech_focus: ['Solar', 'Wind', 'Hydro'],
      mandate_types: ['Equity', 'Mezz'],
      irr_target: 12,
      tags: ['Infrastructure', 'Mid-Market'],
    },
    {
      name: 'Green Transition Fund II',
      summary: 'Project finance provider for utility-scale solar and wind in Southern Europe',
      ticket_min_eur: 50000000,
      ticket_max_eur: 300000000,
      geographies: ['ES', 'PT', 'IT', 'GR'],
      tech_focus: ['Solar', 'Wind'],
      mandate_types: ['Project Finance'],
      irr_target: 8,
      tags: ['Project Finance', 'Large-Scale'],
    },
    {
      name: 'Nordic Clean Capital',
      summary: 'Early-stage equity investor in emerging clean energy technologies',
      ticket_min_eur: 1000000,
      ticket_max_eur: 15000000,
      geographies: ['SE', 'NO', 'DK', 'FI'],
      tech_focus: ['Hydrogen', 'Storage', 'Efficiency'],
      mandate_types: ['Equity'],
      irr_target: 20,
      tags: ['Early-Stage', 'Technology-Focused'],
    },
    {
      name: 'EU Transition Grant Facility',
      summary: 'Grant co-funding for innovative renewable projects with policy alignment',
      ticket_min_eur: 500000,
      ticket_max_eur: 10000000,
      geographies: ['All EU'],
      tech_focus: ['Solar', 'Wind', 'Hydrogen', 'Storage', 'Efficiency'],
      mandate_types: ['Grants'],
      tags: ['Grants', 'Innovation'],
    },
    {
      name: 'Baltic Infrastructure Investors',
      summary: 'Long-term equity partner for operational and near-operational assets',
      ticket_min_eur: 20000000,
      ticket_max_eur: 100000000,
      geographies: ['PL', 'LT', 'LV', 'EE'],
      tech_focus: ['Wind', 'Solar', 'Storage'],
      mandate_types: ['Equity'],
      irr_target: 10,
      tags: ['Operational', 'Long-Term'],
    },
    {
      name: 'Mediterranean Solar Fund',
      summary: 'Specialized solar PV investor across Mediterranean markets',
      ticket_min_eur: 15000000,
      ticket_max_eur: 80000000,
      geographies: ['ES', 'PT', 'IT', 'GR', 'FR'],
      tech_focus: ['Solar'],
      mandate_types: ['Equity', 'Project Finance'],
      irr_target: 11,
      tags: ['Solar', 'Mediterranean'],
    },
    {
      name: 'Offshore Wind Capital Partners',
      summary: 'Dedicated offshore wind development and construction equity',
      ticket_min_eur: 100000000,
      ticket_max_eur: 500000000,
      geographies: ['UK', 'DE', 'DK', 'NL', 'BE'],
      tech_focus: ['Wind'],
      mandate_types: ['Equity'],
      irr_target: 14,
      tags: ['Offshore Wind', 'Large-Scale'],
    },
    {
      name: 'CEE Renewables Fund',
      summary: 'Central and Eastern Europe renewable energy growth equity',
      ticket_min_eur: 5000000,
      ticket_max_eur: 40000000,
      geographies: ['PL', 'CZ', 'RO', 'HU', 'BG'],
      tech_focus: ['Solar', 'Wind', 'Storage'],
      mandate_types: ['Equity'],
      irr_target: 15,
      tags: ['CEE', 'Growth'],
    },
    {
      name: 'Hydrogen Infrastructure Ventures',
      summary: 'Early-stage and development capital for green hydrogen projects',
      ticket_min_eur: 2000000,
      ticket_max_eur: 25000000,
      geographies: ['All EU'],
      tech_focus: ['Hydrogen'],
      mandate_types: ['Equity', 'Mezz'],
      irr_target: 18,
      tags: ['Hydrogen', 'Venture'],
    },
    {
      name: 'Nordic Pension Infrastructure',
      summary: 'Long-term institutional capital for operational renewable assets',
      ticket_min_eur: 50000000,
      ticket_max_eur: 250000000,
      geographies: ['SE', 'NO', 'DK', 'FI'],
      tech_focus: ['Wind', 'Hydro', 'Solar'],
      mandate_types: ['Equity'],
      irr_target: 7,
      tags: ['Pension', 'Low-Risk'],
    },
    {
      name: 'Benelux Energy Transition Fund',
      summary: 'Regional focus on Netherlands, Belgium, and Luxembourg markets',
      ticket_min_eur: 10000000,
      ticket_max_eur: 60000000,
      geographies: ['NL', 'BE', 'LU'],
      tech_focus: ['Solar', 'Wind', 'Storage', 'Hydrogen'],
      mandate_types: ['Equity', 'Project Finance'],
      irr_target: 10,
      tags: ['Benelux', 'Regional'],
    },
    {
      name: 'Storage Solutions Capital',
      summary: 'Dedicated battery storage and flexibility asset investor',
      ticket_min_eur: 8000000,
      ticket_max_eur: 50000000,
      geographies: ['UK', 'DE', 'FR', 'IT', 'ES'],
      tech_focus: ['Storage'],
      mandate_types: ['Equity', 'Project Finance'],
      irr_target: 13,
      tags: ['Storage', 'Grid Services'],
    },
    {
      name: 'Iberian Renewables Debt Fund',
      summary: 'Senior debt provider for Spanish and Portuguese projects',
      ticket_min_eur: 20000000,
      ticket_max_eur: 150000000,
      geographies: ['ES', 'PT'],
      tech_focus: ['Solar', 'Wind'],
      mandate_types: ['Project Finance'],
      irr_target: 6,
      tags: ['Debt', 'Iberia'],
    },
    {
      name: 'European Green Bond Fund',
      summary: 'Green bond issuance and investment for large-scale renewables',
      ticket_min_eur: 50000000,
      ticket_max_eur: 400000000,
      geographies: ['All EU'],
      tech_focus: ['Solar', 'Wind', 'Hydro'],
      mandate_types: ['Project Finance'],
      irr_target: 5,
      tags: ['Green Bonds', 'Institutional'],
    },
    {
      name: 'Community Energy Co-Investment',
      summary: 'Co-investment alongside local community energy groups',
      ticket_min_eur: 500000,
      ticket_max_eur: 5000000,
      geographies: ['DE', 'UK', 'DK', 'AT'],
      tech_focus: ['Solar', 'Wind'],
      mandate_types: ['Equity'],
      irr_target: 9,
      tags: ['Community', 'Small-Scale'],
    },
    {
      name: 'Corporate PPA Fund',
      summary: 'Financing for projects with corporate offtake agreements',
      ticket_min_eur: 15000000,
      ticket_max_eur: 100000000,
      geographies: ['All EU'],
      tech_focus: ['Solar', 'Wind'],
      mandate_types: ['Project Finance', 'Equity'],
      irr_target: 8,
      tags: ['PPA', 'Corporate'],
    },
    {
      name: 'Floating Solar Investment Platform',
      summary: 'Specialized investor in floating PV technology',
      ticket_min_eur: 3000000,
      ticket_max_eur: 30000000,
      geographies: ['NL', 'FR', 'PT', 'IT'],
      tech_focus: ['Solar'],
      mandate_types: ['Equity'],
      irr_target: 16,
      tags: ['Floating Solar', 'Innovation'],
    },
    {
      name: 'Agri-PV Development Fund',
      summary: 'Dual-use agricultural solar project specialist',
      ticket_min_eur: 2000000,
      ticket_max_eur: 20000000,
      geographies: ['DE', 'FR', 'IT', 'ES'],
      tech_focus: ['Solar'],
      mandate_types: ['Equity'],
      irr_target: 14,
      tags: ['Agri-PV', 'Innovation'],
    },
    {
      name: 'European Climate Bank Facility',
      summary: 'Public-backed financing for climate-aligned energy projects',
      ticket_min_eur: 10000000,
      ticket_max_eur: 200000000,
      geographies: ['All EU'],
      tech_focus: ['Solar', 'Wind', 'Hydrogen', 'Storage', 'Efficiency'],
      mandate_types: ['Project Finance', 'Grants'],
      tags: ['Public Finance', 'Climate'],
    },
  ];

  const suppliers = [
    {
      name: 'SolarBuild Europe',
      role: 'EPC',
      summary: 'Full-service EPC contractor for utility-scale solar projects',
      geographies: ['ES', 'PT', 'IT', 'FR', 'GR'],
      technologies: ['Solar'],
      capacity_mw_py: 800,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2023 },
        { name: 'ISO 14001', issuer: 'ISO', year: 2023 },
      ],
      tags: ['Solar EPC', 'Utility-Scale'],
    },
    {
      name: 'WindTech Systems',
      role: 'OEM',
      summary: 'Manufacturer of onshore and offshore wind turbines, 5-15 MW class',
      geographies: ['All EU'],
      technologies: ['Wind'],
      capacity_mw_py: 2000,
      credentials: [
        { name: 'IEC 61400 Certification', issuer: 'IEC', year: 2024 },
      ],
      tags: ['Wind Turbines', 'OEM'],
    },
    {
      name: 'GreenGrid Consulting',
      role: 'Consulting',
      summary: 'Grid integration and permitting advisory for renewable projects',
      geographies: ['DE', 'NL', 'BE', 'DK', 'AT'],
      technologies: ['Solar', 'Wind', 'Storage', 'Hydrogen'],
      tags: ['Consulting', 'Grid', 'Permitting'],
    },
    {
      name: 'HydroCell Technologies',
      role: 'OEM',
      summary: 'Electrolyzer and fuel cell manufacturer for green hydrogen applications',
      geographies: ['All EU'],
      technologies: ['Hydrogen'],
      capacity_mw_py: 500,
      credentials: [
        { name: 'PED Certification', issuer: 'EU', year: 2024 },
      ],
      tags: ['Hydrogen', 'Electrolyzer', 'OEM'],
    },
    {
      name: 'BatteryStore Solutions',
      role: 'EPC',
      summary: 'Turnkey battery storage system integrator',
      geographies: ['UK', 'IE', 'FR', 'BE', 'NL'],
      technologies: ['Storage'],
      capacity_mw_py: 300,
      credentials: [
        { name: 'ISO 9001', issuer: 'ISO', year: 2023 },
      ],
      tags: ['Battery', 'Storage', 'EPC'],
    },
    {
      name: 'EuroEnergy Advisory',
      role: 'Consulting',
      summary: 'Financial modeling, due diligence, and transaction advisory for energy projects',
      geographies: ['All EU'],
      technologies: ['Solar', 'Wind', 'Storage', 'Hydro', 'Hydrogen', 'Efficiency'],
      tags: ['Financial Advisory', 'Due Diligence'],
    },
  ];

  const policyBriefs = [
    {
      country: 'ES',
      country_name: 'Spain',
      incentives: [
        {
          name: 'PERTE Renovables',
          description: 'Strategic project for renewable energy and green hydrogen',
          eligibility: 'Projects above 5 MW with domestic content requirements',
          amount: 'Up to 30% CAPEX grant',
        },
      ],
      permitting_steps: [
        {
          step: 1,
          name: 'Environmental Impact Assessment',
          description: 'Submit EIA documentation to regional authority',
          typical_duration: '6-12 months',
          agency: 'Regional Environmental Agency',
        },
        {
          step: 2,
          name: 'Grid Access Permit',
          description: 'Apply for grid connection point and capacity allocation',
          typical_duration: '3-6 months',
          agency: 'Red Eléctrica de España',
        },
        {
          step: 3,
          name: 'Construction Permit',
          description: 'Obtain local construction authorization',
          typical_duration: '2-4 months',
          agency: 'Municipal Authority',
        },
      ],
      avg_lead_times: {
        solar: '12-18 months',
        wind: '18-36 months',
      },
      agencies: [
        { name: 'MITECO', role: 'National energy and environment ministry', website: 'miteco.gob.es' },
        { name: 'IDAE', role: 'Energy efficiency and renewable promotion', website: 'idae.es' },
      ],
      sources: [
        { title: 'Royal Decree 1183/2020 on Grid Access', url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2020-17771' },
        { title: 'PERTE ERHA Information (IDAE)', url: 'https://www.idae.es/ayudas-y-financiacion/para-empresas/perte-erha' },
        { title: 'Spanish NECP 2021-2030', url: 'https://energy.ec.europa.eu/system/files/2020-06/es_final_necp_main_en_0.pdf' },
      ],
    },
    {
      country: 'DE',
      country_name: 'Germany',
      incentives: [
        {
          name: 'EEG Feed-in Premium',
          description: 'Market premium for renewable electricity',
          eligibility: 'Competitive auction participation',
          amount: 'Variable, auction-determined',
        },
        {
          name: 'H2Global Program',
          description: 'Support for green hydrogen imports and domestic production',
          eligibility: 'Hydrogen projects with verified green credentials',
          amount: 'Price differential contracts',
        },
      ],
      permitting_steps: [
        {
          step: 1,
          name: 'BImSchG Approval',
          description: 'Federal Immission Control Act permit for large installations',
          typical_duration: '6-12 months',
          agency: 'State Environmental Authority',
        },
        {
          step: 2,
          name: 'Grid Connection Agreement',
          description: 'Secure connection with TSO or DSO',
          typical_duration: '4-8 months',
          agency: 'Transmission/Distribution System Operator',
        },
        {
          step: 3,
          name: 'Building Permit',
          description: 'Local construction authorization',
          typical_duration: '2-3 months',
          agency: 'Local Building Authority',
        },
      ],
      avg_lead_times: {
        solar: '10-16 months',
        wind: '24-48 months',
        hydrogen: '18-30 months',
      },
      agencies: [
        { name: 'BMWi', role: 'Federal Ministry for Economic Affairs and Energy', website: 'bmwk.de' },
        { name: 'BNetzA', role: 'Federal Network Agency', website: 'bundesnetzagentur.de' },
      ],
      sources: [
        { title: 'EEG 2023 (Renewable Energy Act)', url: 'https://www.gesetze-im-internet.de/eeg_2014/index.html' },
        { title: 'German Hydrogen Strategy', url: 'https://www.bmwk.de/Redaktion/EN/Publikationen/Energie/the-national-hydrogen-strategy.html' },
        { title: 'German NECP', url: 'https://energy.ec.europa.eu/system/files/2020-03/de_final_necp_main_en_0.pdf' },
      ],
    },
    {
      country: 'FR',
      country_name: 'France',
      incentives: [
        {
          name: 'CRE Tender Program',
          description: 'Competitive tenders for renewable projects',
          eligibility: 'Projects above threshold capacity',
          amount: 'Auction-determined feed-in tariff',
        },
      ],
      permitting_steps: [
        {
          step: 1,
          name: 'Environmental Authorization',
          description: 'Unified environmental permit (permis environnemental unique)',
          typical_duration: '9-12 months',
          agency: 'Prefect / DREAL',
        },
        {
          step: 2,
          name: 'Grid Connection',
          description: 'Proposal and agreement with Enedis/RTE',
          typical_duration: '4-6 months',
          agency: 'Enedis or RTE',
        },
        {
          step: 3,
          name: 'Building Permit',
          description: 'Local construction permit (permis de construire)',
          typical_duration: '2-3 months',
          agency: 'Municipal Authority',
        },
      ],
      avg_lead_times: {
        solar: '12-18 months',
        wind: '24-36 months',
      },
      agencies: [
        { name: 'CRE', role: 'Energy Regulatory Commission', website: 'cre.fr' },
        { name: 'ADEME', role: 'Ecological Transition Agency', website: 'ademe.fr' },
      ],
      sources: [
        { title: 'French Energy Transition Law (LTECV)', url: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000031044385' },
        { title: 'French NECP', url: 'https://energy.ec.europa.eu/system/files/2020-06/fr_final_necp_main_en_0.pdf' },
        { title: 'PPE - Multi-Year Energy Plan', url: 'https://www.ecologie.gouv.fr/programmations-pluriannuelles-lenergie-ppe' },
      ],
    },
  ];

  const gridBriefs = [
    {
      country: 'ES',
      country_name: 'Spain',
      steps: [
        {
          step: 1,
          name: 'Pre-application Consultation',
          description: 'Discuss project with TSO/DSO',
          typical_duration: '1 month',
        },
        {
          step: 2,
          name: 'Grid Access Request',
          description: 'Formal application and capacity check',
          typical_duration: '3-6 months',
        },
        {
          step: 3,
          name: 'Connection Agreement',
          description: 'Sign agreement and pay deposits',
          typical_duration: '2-3 months',
        },
        {
          step: 4,
          name: 'Construction and Commissioning',
          description: 'Build connection assets and test',
          typical_duration: '6-12 months',
        },
      ],
      lead_time_min_months: 12,
      lead_time_max_months: 24,
      queue_notes: 'Significant queue in high-generation areas; prioritization for storage',
      documents: [
        { name: 'Technical Project Description', description: 'Detailed technical specs and layout' },
        { name: 'Land Rights Documentation', description: 'Proof of land control or easements' },
        { name: 'Environmental Clearance', description: 'EIA approval certificate' },
      ],
      sources: [
        { title: 'REE Grid Connection Procedures', url: 'https://www.ree.es/en/activities/access-and-connection' },
      ],
    },
    {
      country: 'DE',
      country_name: 'Germany',
      steps: [
        {
          step: 1,
          name: 'Informal Inquiry',
          description: 'Initial capacity and feasibility check',
          typical_duration: '1 month',
        },
        {
          step: 2,
          name: 'Formal Application',
          description: 'Submit full connection request',
          typical_duration: '4-6 months',
        },
        {
          step: 3,
          name: 'Connection Offer',
          description: 'Receive and accept connection terms',
          typical_duration: '2-4 months',
        },
        {
          step: 4,
          name: 'Implementation',
          description: 'Build connection infrastructure',
          typical_duration: '12-18 months',
        },
      ],
      lead_time_min_months: 18,
      lead_time_max_months: 36,
      queue_notes: 'North-South bottlenecks; offshore wind has dedicated capacity',
      documents: [
        { name: 'Plant Description', description: 'Technical specs per VDE standards' },
        { name: 'Site Plan', description: 'Detailed layout and grid interface' },
        { name: 'BImSchG Permit', description: 'Environmental approval' },
      ],
      sources: [
        { title: 'BNetzA Grid Connection Info', url: 'https://www.bundesnetzagentur.de/EN/Areas/Energy/Companies/GridConnection/start.html' },
      ],
    },
    {
      country: 'FR',
      country_name: 'France',
      steps: [
        {
          step: 1,
          name: 'Pre-study Request',
          description: 'Request grid capacity assessment',
          typical_duration: '1-2 months',
        },
        {
          step: 2,
          name: 'Full Study and Proposal',
          description: 'Detailed technical and cost proposal from TSO/DSO',
          typical_duration: '4-6 months',
        },
        {
          step: 3,
          name: 'Agreement Signature',
          description: 'Sign PTF (Proposal Technique et Financière)',
          typical_duration: '2 months',
        },
        {
          step: 4,
          name: 'Works Execution',
          description: 'Grid reinforcement and connection construction',
          typical_duration: '6-12 months',
        },
      ],
      lead_time_min_months: 13,
      lead_time_max_months: 22,
      queue_notes: 'Regional variations; southern regions have faster timelines',
      documents: [
        { name: 'Project Description', description: 'Technical dossier per NF standards' },
        { name: 'Environmental Authorization', description: 'Permis environnemental unique' },
        { name: 'Land Availability', description: 'Proof of site control' },
      ],
      sources: [
        { title: 'RTE Connection Procedures', url: 'https://www.rte-france.com/en/connections-and-suppliers-portal' },
        { title: 'Enedis Connection Portal', url: 'https://www.enedis.fr/raccordement-production' },
      ],
    },
  ];

  const events = [
    {
      title: 'European Clean Energy Forum 2026',
      description: 'Annual gathering of projects, investors, and policymakers across European renewable energy',
      start_date: '2026-03-15',
      end_date: '2026-03-17',
      location: 'Brussels, Belgium',
      event_type: 'Conference',
      sessions: [
        {
          id: 's1',
          title: 'Offshore Wind: Scaling to 100 GW',
          description: 'Panel on offshore wind targets and supply chain challenges',
          start_time: '2026-03-15T09:00:00',
          end_time: '2026-03-15T10:30:00',
          track: 'Technology',
          speakers: ['Jane Doe', 'John Smith'],
        },
        {
          id: 's2',
          title: 'Green Hydrogen Economics',
          description: 'Current costs, subsidies, and pathways to competitiveness',
          start_time: '2026-03-15T11:00:00',
          end_time: '2026-03-15T12:30:00',
          track: 'Market',
          speakers: ['Maria Garcia', 'Lars Nielsen'],
        },
        {
          id: 's3',
          title: 'Permitting Reform: Progress and Gaps',
          description: 'Update on EU and member-state permitting acceleration',
          start_time: '2026-03-15T14:00:00',
          end_time: '2026-03-15T15:30:00',
          track: 'Policy',
          speakers: ['Policy Expert 1', 'Policy Expert 2'],
        },
      ],
      tags: ['Conference', 'Brussels', '2026'],
    },
  ];

  const libraryItems = [
    {
      title: 'Understanding EU Renewable Energy Directive (RED III)',
      summary: 'Plain-English breakdown of the revised Renewable Energy Directive and its implications for project developers',
      content: 'The EU Renewable Energy Directive (RED III) sets binding targets for renewable energy across member states. Key updates include accelerated permitting timelines (maximum 12 months for solar, 24 months for wind in designated areas), mandatory go-to areas for renewables, and strengthened sustainability criteria. For developers, this means streamlined processes in designated zones, but stricter environmental safeguards. Member states must transpose RED III by mid-2024, with implementation timelines varying by country. Practical impact: Projects in designated renewable acceleration areas benefit from presumed public interest and simplified environmental assessments.',
      item_type: 'Brief',
      read_time_minutes: 2,
      tags: ['Policy', 'EU', 'Permitting'],
    },
    {
      title: 'Grid Connection Queue Management Across Europe',
      summary: 'Comparative analysis of how different countries handle grid connection applications and queue priorities',
      content: 'Grid connection queues vary significantly across Europe. Germany employs a first-come-first-served model with conditional milestones, while Spain recently reformed its system to prioritize projects with advanced development status. France uses a mixed approach with regional capacity allocation. Key insight: Storage projects are increasingly receiving priority treatment due to grid stabilization benefits. Best practice for developers: secure grid capacity early, maintain milestone compliance, and consider hybrid projects (solar + storage) for preferential treatment. Typical queue times range from 12 months (France, distribution level) to 36+ months (Germany, transmission level).',
      item_type: 'Brief',
      read_time_minutes: 2,
      tags: ['Grid', 'Infrastructure', 'Permitting'],
    },
    {
      title: 'Green Hydrogen Production Costs: 2024 Benchmark',
      summary: 'Current levelized cost breakdown for electrolytic hydrogen production in Europe',
      content: 'As of 2024, green hydrogen production costs in Europe range from €4-7/kg depending on electricity prices, electrolyzer efficiency, and utilization rates. Key cost drivers: renewable electricity (50-60% of LCOH), electrolyzer CAPEX (25-30%), and O&M (10-15%). Costs are falling rapidly—electrolyzer prices dropped 40% since 2020. Pathways to competitiveness: securing low-cost PPAs (target <€30/MWh), achieving high capacity factors (>4,000 hours/year), and accessing grant support (IPCEI, H2Global). Projects with co-located renewables and merchant offtake are reaching €3.5-4.5/kg in Iberia and Northern Europe. Policy support remains critical—most projects rely on CAPEX grants or price guarantees to close the gap with grey hydrogen (€1.5-2.5/kg).',
      item_type: 'Brief',
      read_time_minutes: 3,
      tags: ['Hydrogen', 'Economics', 'Technology'],
    },
  ];

  const { error: projectsError } = await supabase.from('projects').insert(projects);
  if (projectsError) console.error('Projects error:', projectsError);
  else console.log(`✓ Inserted ${projects.length} projects`);

  const { error: investorsError } = await supabase.from('investors').insert(investors);
  if (investorsError) console.error('Investors error:', investorsError);
  else console.log(`✓ Inserted ${investors.length} investors`);

  const { error: suppliersError } = await supabase.from('suppliers').insert(suppliers);
  if (suppliersError) console.error('Suppliers error:', suppliersError);
  else console.log(`✓ Inserted ${suppliers.length} suppliers`);

  const { error: policyError } = await supabase.from('policy_briefs').insert(policyBriefs);
  if (policyError) console.error('Policy briefs error:', policyError);
  else console.log(`✓ Inserted ${policyBriefs.length} policy briefs`);

  const { error: gridError } = await supabase.from('grid_briefs').insert(gridBriefs);
  if (gridError) console.error('Grid briefs error:', gridError);
  else console.log(`✓ Inserted ${gridBriefs.length} grid briefs`);

  const { error: eventsError } = await supabase.from('events').insert(events);
  if (eventsError) console.error('Events error:', eventsError);
  else console.log(`✓ Inserted ${events.length} events`);

  const { error: libraryError } = await supabase.from('library_items').insert(libraryItems);
  if (libraryError) console.error('Library items error:', libraryError);
  else console.log(`✓ Inserted ${libraryItems.length} library items`);

  console.log('✅ Seeding complete!');
}

seed().catch(console.error);
